name: Publish Python Package

on:
  release:
    types: [published]
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        python -m poetry install --with dev
    - name: Build package
      run: python -m poetry build
    - name: Publish package
      run: python -m poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
